# === Netlify Configuration File (Final Version) ===

[build]
  # The directory where your project is located, relative to the repo root.
  base = "my-web"

  # Build command: A command to run to force function bundling.
  command = "echo 'Building...'"

  # The directory to publish, relative to the base directory.
  # "." means the root of the base directory ("my-web").
  publish = "."

  # The directory where your serverless functions are.
  functions = "netlify/functions"

# --- ADD THIS SECTION ---
# This plugin automatically installs dependencies from your function's package.json
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
